openapi: 3.0.3
info:
  title: Health API
  description: Health check endpoint for all services
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
  license:
    name: Proprietary
servers:
  - url: /api/v1
    description: Production server
paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns 200 OK if the service is running properly
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: Current health status of the service