openapi: 3.0.3
info:
  title: Flight Management
  description: API for flight management
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
  license:
    name: Proprietary
servers:
  - url: /api/v1
    description: Production server
paths:
  /flights:
    post:
      summary: Create a new flight
      description: Creates a new flight schedule and triggers journey generation
      operationId: createFlight
      tags:
        - Flights
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFlightRequest'
      responses:
        '201':
          description: Flight created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Flight already exists with the same details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /bookings:
    post:
      summary: Create a new booking
      description: Creates a booking for a journey with seat reservation and payment
      operationId: createBooking
      tags:
        - Bookings
      parameters:
        - name: userId
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookingRequest'
      responses:
        '201':
          description: Booking created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingResponse'
        '400':
          description: Invalid booking request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Insufficient seats available or booking conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Journey not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /bookings/{booking_id}:
    get:
      summary: Get booking details
      description: Retrieve details of a specific booking
      operationId: getBooking
      tags:
        - Bookings
      parameters:
        - name: booking_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier for the booking
      responses:
        '200':
          description: Booking details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingResponse'
        '404':
          description: Booking not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /journeys/search:
    get:
      summary: Search for flight journeys
      description: Search for single or multi-leg flight journeys based on criteria
      operationId: searchJourneys
      tags:
        - Search
      parameters:
        - name: source_airport
          in: query
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 3
            pattern: '^[A-Z]{3}$'
          description: Three-letter source airport code
        - name: destination_airport
          in: query
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 3
            pattern: '^[A-Z]{3}$'
          description: Three-letter destination airport code
        - name: departure_date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Departure date in YYYY-MM-DD format
        - name: passengers
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 9
          description: Number of passengers
        - name: sort_by
          in: query
          required: false
          schema:
            type: string
            enum: [ price, duration ]
          description: Sort results by price (cheapest first) or duration (fastest first)
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: Maximum number of results to return
      responses:
        '200':
          description: Search results found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '400':
          description: Invalid search parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    SearchResponse:
      type: object
      properties:
        journeys:
          type: array
          items:
            $ref: '#/components/schemas/Journey'
          description: List of matching journeys
        total_count:
          type: integer
          description: Total number of journeys found
    Journey:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the journey
        departure_time:
          type: string
          format: date-time
          description: Departure time of the first flight in the journey
        arrival_time:
          type: string
          format: date-time
          description: Arrival time of the last flight in the journey
        total_price:
          type: number
          description: Total price for the journey in USD
        layover_count:
          type: integer
          description: Number of layovers (0 for direct flights)
        flights:
          type: array
          items:
            $ref: '#/components/schemas/FlightReference'
          minItems: 1
          maxItems: 3
          description: List of flight segments in order
        available_seats:
          type: integer
          description: Minimum available seats across all flights in journey
    Flight:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the flight
        source_airport:
          type: string
          description: Three-letter source airport code
        destination_airport:
          type: string
          description: Three-letter destination airport code
        departure_time:
          type: string
          format: date-time
          description: Flight departure time in ISO 8601 format
        arrival_time:
          type: string
          format: date-time
          description: Flight arrival time in ISO 8601 format
        price:
          type: number
          description: Flight price in USD
        airplane_tail_number:
          type: string
          description: Tail number of the airplane
    FlightReference:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the flight
        order:
          type: integer
          minimum: 1
          maximum: 3
          description: Order of this flight in the journey
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message describing what went wrong
        details:
          type: string
          description: Additional details about the error
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the error occurred
    CreateBookingRequest:
      type: object
      required:
        - journey_id
        - passenger_count
        - passenger_details
        - payment_id
      properties:
        journey_id:
          type: string
          format: uuid
          description: UUID of the journey to book
        passenger_count:
          type: integer
          minimum: 1
          maximum: 9
          description: Number of passengers for this booking
        payment_id:
          type: string
          description: Payment transaction ID for this booking
    BookingResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the booking
        journey_id:
          type: string
          format: uuid
          description: UUID of the booked journey
        passenger_count:
          type: integer
          description: Number of passengers in this booking
        total_price:
          type: number
          description: Total price paid for the booking in USD
        status:
          type: string
          enum: [ CONFIRMED, PENDING, CANCELLED, RESERVED ]
          description: Current status of the booking
        payment_id:
          type: string
          description: Payment transaction ID for this booking
        seat_assignments:
          type: array
          items:
            $ref: '#/components/schemas/SeatAssignment'
          description: Seat assignments for each flight in the journey
        journey_details:
          $ref: '#/components/schemas/JourneyDetails'
        created_at:
          type: string
          format: date-time
          description: Timestamp when the booking was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the booking was last updated
    SeatAssignment:
      type: object
      properties:
        flight_id:
          type: string
          format: uuid
          description: UUID of the flight
        seat_numbers:
          type: array
          items:
            type: string
          description: List of assigned seat numbers for this flight
    JourneyDetails:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the journey
        departure_time:
          type: string
          format: date-time
          description: Departure time of the first flight in the journey
        arrival_time:
          type: string
          format: date-time
          description: Arrival time of the last flight in the journey
        layover_count:
          type: integer
          description: Number of layovers (0 for direct flights)
        flights:
          type: array
          items:
            $ref: '#/components/schemas/FlightReference'
          description: List of flight segments in order
    CreateFlightRequest:
      type: object
      required:
        - source_airport
        - destination_airport
        - departure_time
        - arrival_time
        - airplane_id
        - price
        - total_seats
      properties:
        source_airport:
          type: string
          minLength: 3
          maxLength: 3
          pattern: '^[A-Z]{3}$'
          description: Three-letter source airport code
        destination_airport:
          type: string
          minLength: 3
          maxLength: 3
          pattern: '^[A-Z]{3}$'
          description: Three-letter destination airport code
        departure_time:
          type: string
          format: date-time
          description: Flight departure time in ISO 8601 format
        arrival_time:
          type: string
          format: date-time
          description: Flight arrival time in ISO 8601 format
        airplane_id:
          type: string
          format: uuid
          description: UUID of the airplane assigned to this flight
        price:
          type: number
          minimum: 0
          description: Flight price in USD
        total_seats:
          type: integer
          minimum: 1
          maximum: 500
          description: Total number of seats available on this flight
    FlightResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the flight
        source_airport:
          type: string
          description: Three-letter source airport code
        destination_airport:
          type: string
          description: Three-letter destination airport code
        departure_time:
          type: string
          format: date-time
          description: Flight departure time in ISO 8601 format
        arrival_time:
          type: string
          format: date-time
          description: Flight arrival time in ISO 8601 format
        airplane_id:
          type: string
          format: uuid
          description: UUID of the airplane assigned to this flight
        price:
          type: number
          description: Flight price in USD
        total_seats:
          type: integer
          description: Total number of seats available on this flight
        available_seats:
          type: integer
          description: Number of available seats for booking
        created_at:
          type: string
          format: date-time
          description: Timestamp when the flight was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the flight was last updated
